// Generated by src/utils/build-icons.mjs — do not edit.

/** @typedef {'add-user-male' | 'calendar' | 'chat-bubble' | 'check-mark' | 'condo' | 'done' | 'file-explorer' | 'file' | 'lock' | 'multiply' | 'open-parcel' | 'pencil' | 'plus-math' | 'spinner' | 'us-dollar-circled' | 'user' | 'worker'} IconName */

export const ICON_NAMES = [
  'add-user-male',
  'calendar',
  'chat-bubble',
  'check-mark',
  'condo',
  'done',
  'file-explorer',
  'file',
  'lock',
  'multiply',
  'open-parcel',
  'pencil',
  'plus-math',
  'spinner',
  'us-dollar-circled',
  'user',
  'worker',
];
