import React from "react";
import {
  Modal,
  Box,
  Typography,
  Divider,
  Button,
  Table,
  TableHead,
  TableRow,
  TableCell,
  TableBody,
  TableContainer,
  Paper
} from "@mui/material";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useTranslation } from "react-i18next";
import { toast } from "react-toastify";
import LockIcon from "@mui/icons-material/Lock";

const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: { xs: "95%", md: 900 },
  maxHeight: "80vh",
  overflowY: "auto",
  bgcolor: "background.paper",
  borderRadius: 3,
  boxShadow: 24,
  p: 4
};

export default function InventoryBreakdownModal({open,handleClose,items}) {
  console.log(items)
  const { t } = useTranslation();
  const totalPurchased = items.reduce(
    (sum, item) => sum + item.totalQuantity * item.pricePerUnit,
    0
  );

  const totalRemaining = items.reduce(
    (sum, item) => sum + item.availableQuantity * item.pricePerUnit,
    0
  );

  const totalUsed = totalPurchased - totalRemaining;

  const exportPDF = () => {
    if (!items || items.length === 0) return;

    // Landscape A4 for better width
    const doc = new jsPDF("landscape", "mm", "a4");

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const projectName = items[0]?.projectId?.title || "N/A";
    const contractorName =
      items[0]?.projectId?.contractor?.name || "N/A";

    const today = new Date().toLocaleDateString();

    // ===== HEADER BAR =====
    doc.setFillColor(95, 163, 45);
    doc.rect(0, 0, pageWidth, 25, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(0);
    doc.text("Inventory Cost Breakdown", 14, 16);

    // ===== PROJECT INFO =====
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    doc.text(`Project: ${projectName}`, 14, 35);
    doc.text(`Contractor: ${contractorName}`, 14, 42);
    doc.text(`Generated On: ${today}`, 14, 49);

    // ===== TABLE =====
    const tableData = items.map((item) => [
      item.name,
      item.unit,
      item.pricePerUnit.toLocaleString(),
      item.totalQuantity,
      item.availableQuantity,
      (item.totalQuantity * item.pricePerUnit).toLocaleString(),
      (item.availableQuantity * item.pricePerUnit).toLocaleString()
    ]);

    autoTable(doc, {
      startY: 55,
      head: [[
        "Material",
        "Unit",
        "Price",
        "Purchased",
        "Remaining",
        "Purchased Value",
        "Remaining Value"
      ]],
      body: tableData,
      theme: "grid",
      styles: {
        fontSize: 9,
        cellPadding: 3
      },
      headStyles: {
        fillColor: [95, 163, 45],
        textColor: 0,
        fontStyle: "bold"
      },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 25 },
        2: { halign: "right", cellWidth: 30 },
        3: { halign: "right", cellWidth: 30 },
        4: { halign: "right", cellWidth: 30 },
        5: { halign: "right", cellWidth: 40 },
        6: { halign: "right", cellWidth: 40 }
      }
    });

    // ===== CALCULATIONS =====
    const totalPurchased = items.reduce(
      (sum, item) => sum + item.totalQuantity * item.pricePerUnit,
      0
    );

    const totalRemaining = items.reduce(
      (sum, item) => sum + item.availableQuantity * item.pricePerUnit,
      0
    );

    const totalUsed = totalPurchased - totalRemaining;

    const finalY = doc.lastAutoTable.finalY + 15;


    // ===== TOTALS BOX  =====
doc.setDrawColor(200);

// Left margin same as content (14)
const boxX = 14;
const boxWidth = 110;

doc.rect(boxX, finalY - 8, boxWidth, 30);

doc.setFont("helvetica", "bold");
doc.setFontSize(11);

// Left aligned text inside box
doc.text(
  `Total Purchased: Rs. ${totalPurchased.toLocaleString()}`,
  boxX + 5,
  finalY
);

doc.text(
  `Total Used: Rs. ${totalUsed.toLocaleString()}`,
  boxX + 5,
  finalY + 8
);

doc.text(
  `Total Remaining: Rs. ${totalRemaining.toLocaleString()}`,
  boxX + 5,
  finalY + 16
);

    // ===== FOOTER =====
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120);

    doc.text(
      "Generated by ODRABUILD Construction Management System",
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );

    doc.save(`Inventory-${projectName}.pdf`);
  };

  return (
    <Modal open={open} onClose={handleClose}>
      <Box sx={style}>

        <Typography variant="h6"  gutterBottom>
          {t("inventory.cost_breakdown")}
        </Typography>

        <Divider sx={{ mb: 3 }} />

        <TableContainer component={Paper} sx={{ mb: 3 }}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell><strong>{t("inventory.material")}</strong></TableCell>
                <TableCell><strong>{t("inventory.unit")}</strong></TableCell>
                <TableCell><strong>{t("inventory.price_per_unit")}</strong></TableCell>
                <TableCell><strong>{t("inventory.purchased_qty")}</strong></TableCell>
                <TableCell><strong>{t("inventory.remaining_qty")}</strong></TableCell>
                <TableCell><strong>{t("inventory.purchased_value")}</strong></TableCell>
                <TableCell><strong>{t("inventory.remaining_value")}</strong></TableCell>
              </TableRow>
            </TableHead>

            <TableBody>
              {items.map((item) => (
                <TableRow key={item._id}>
                  <TableCell>{item.name}</TableCell>
                  <TableCell>{item.unit}</TableCell>
                  <TableCell>₹ {item.pricePerUnit}</TableCell>
                  <TableCell>{item.totalQuantity}</TableCell>
                  <TableCell>{item.availableQuantity}</TableCell>
                  <TableCell>
                    ₹ {item.totalQuantity * item.pricePerUnit}
                  </TableCell>
                  <TableCell>
                    ₹ {item.availableQuantity * item.pricePerUnit}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>

        <Divider sx={{ my: 2 }} />

        <Typography variant="h6">
        {t("inventory.total_purchased_value")}: ₹ {totalPurchased}
        </Typography>

        <Typography variant="h6" sx={{ mt: 1 }}>
        {t("inventory.total_used_cost")}: ₹ {totalUsed}
        </Typography>

        <Typography variant="h6" sx={{ mt: 1 }}>
          {t("inventory.remaining_stock_value")}: ₹ {totalRemaining}
        </Typography>

        <Box sx={{ textAlign: "right", mt: 3, display: "flex", gap: 2, justifyContent: "flex-end" }}>

          <Button
            variant="outlined"
            onClick={() => {

              exportPDF();
            }}
            disabled={items.length === 0}
            sx={{
              borderColor: false ? "#ccc" : "#F97316",
              color: false ? "#999" : "#000",
              fontWeight: 600,
              opacity: false ? 0.6 : 1,
              display: "flex",
              alignItems: "center",
              gap: "6px"
            }}
          >
            {t("inventory.export_pdf")}

            {false && (
              <LockIcon sx={{ fontSize: 16, color: "#ff9800" }} />
            )}
          </Button>

          <Button
            variant="contained"
            onClick={handleClose}
            sx={{
              backgroundColor: "primary.main",
              color: "#000",
              fontWeight: 600,
              "&:hover": {
                backgroundColor: "white"
              },
            }}
          >
            {t("inventory.close")}
          </Button>
        </Box>

      </Box>
    </Modal>
  );
}
