#!/usr/bin/env node
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

const SRC = 'public/assets/icons';
const SPRITE = 'public/icons.svg';
const NAMES = 'src/components/atoms/Icon/icon-names.js';

const files = readdirSync(SRC).filter((f) => f.endsWith('.svg')).sort();
const invalid = files.filter((f) => !/^icon-[a-z0-9-]+\.svg$/.test(f));
if (invalid.length) {
  console.error(`[icons] rename to icon-<kebab-name>.svg: ${invalid.join(', ')}`);
  process.exit(1);
}

const symbols = files.map((file) => {
  const id = basename(file, '.svg'); // icon-trash
  const raw = readFileSync(join(SRC, file), 'utf8');
  const viewBox = raw.match(/viewBox=["']([^"']+)/)?.[1] ?? '0 0 24 24';
  const inner = (raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i)?.[1] ?? '')
    // Scope internal ids: downloaded SVGs reuse ids like "clip0", and duplicates
    // inside one sprite make icons borrow each other's clipPaths/gradients.
    .replace(/\bid="([^"]+)"/g, `id="${id}__$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#${id}__$1)`)
    .replace(/href="#([^"]+)"/g, `href="#${id}__$1"`)
    .trim();
  return `<symbol id="${id}" viewBox="${viewBox}">${inner}</symbol>`;
});
writeFileSync(SPRITE, `<svg xmlns="http://www.w3.org/2000/svg">\n${symbols.join('\n')}\n</svg>\n`);

const names = files.map((f) => f.slice('icon-'.length, -'.svg'.length));
writeFileSync(
  NAMES,
  `// Generated by scripts/build-icons.mjs — do not edit.\n\n` +
    `/** @typedef {${names.map((n) => `'${n}'`).join(' | ')}} IconName */\n\n` +
    `export const ICON_NAMES = [\n${names.map((n) => `  '${n}',`).join('\n')}\n];\n`,
);

console.log(`[icons] ${names.length} icons → icons.svg + icon-names.js`);
