#!/usr/bin/env node
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const SRC = join(PROJECT_ROOT, 'src/assets/icons');
const PUBLIC = join(PROJECT_ROOT, 'public');
const SPRITE = join(PUBLIC, 'icons.svg');
const PUBLIC_ICONS = join(PUBLIC, 'icons');
const NAMES = join(PROJECT_ROOT, 'src/Components/atoms/Icon/icon-names.js');

const files = readdirSync(SRC).filter((f) => f.endsWith('.svg')).sort();
const invalid = files.filter((f) => !/^icon-[a-z0-9-]+\.svg$/.test(f));
if (invalid.length) {
  console.error(`[icons] rename to icon-<kebab-name>.svg: ${invalid.join(', ')}`);
  process.exit(1);
}

mkdirSync(PUBLIC_ICONS, { recursive: true });

const symbols = files.map((file) => {
  const id = basename(file, '.svg'); // icon-trash
  const raw = readFileSync(join(SRC, file), 'utf8');
  const viewBox = raw.match(/viewBox=["']([^"']+)/)?.[1] ?? '0 0 24 24';
  const rootFilter = raw.match(/<svg\b[^>]*\bfilter=["']url\(#([^)"']+)\)["']/)?.[1];
  const inner = (raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i)?.[1] ?? '')
    // Scope internal ids: downloaded SVGs reuse ids like "clip0", and duplicates
    // inside one sprite make icons borrow each other's clipPaths/gradients.
    .replace(/\bid="([^"]+)"/g, `id="${id}__$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#${id}__$1)`)
    .replace(/href="#([^"]+)"/g, `href="#${id}__$1"`)
    .trim();
  const contents = rootFilter ? `<g filter="url(#${id}__${rootFilter})">${inner}</g>` : inner;
  return `<symbol id="${id}" viewBox="${viewBox}">${contents}</symbol>`;
});
writeFileSync(
  SPRITE,
  `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n${symbols.join('\n')}\n</svg>\n`,
);

const names = files.map((f) => f.slice('icon-'.length, -'.svg'.length));
writeFileSync(
  NAMES,
  `// Generated by src/utils/build-icons.mjs — do not edit.\n\n` +
    `/** @typedef {${names.map((n) => `'${n}'`).join(' | ')}} IconName */\n\n` +
    `export const ICON_NAMES = [\n${names.map((n) => `  '${n}',`).join('\n')}\n];\n`,
);

for (const file of files) {
  copyFileSync(join(SRC, file), join(PUBLIC_ICONS, file));
}

console.log(`[icons] ${names.length} icons → icons.svg + icon-names.js`);
